PROJECT := 'findbugs-1.3.9'
INSTRUMENT_CLASSES := 'edu.umd.cs.findbugs.**'
CUSTOM_MUTATOR := 'libzipcompressionmutator.so'
COVERAGE_INCLUDES := 'edu.umd.cs.findbugs.**'
COVERAGE_EXCLUDES := ''

build_project: build_java

prepare_corpus EXPERIMENT:
    cp -r {{BASE_DIR}}/fuzzing-corpora/fatjars/seed-corpus/* {{TARGET_PATH}}/{{EXPERIMENT}}/corpus
    cp -r {{BASE_DIR}}/fuzzing-corpora/fatjars/dict.txt {{TARGET_PATH}}/{{EXPERIMENT}}/dict.txt

import '../Justfile'