PROJECT := 'hsqldb-2.7.4'
INSTRUMENT_CLASSES := 'org.hsqldb.**'
COVERAGE_INCLUDES := 'org.hsqldb.**'
COVERAGE_EXCLUDES := ''

build_project: build_java

prepare_corpus EXPERIMENT:
    cp -r {{BASE_DIR}}/fuzzing-corpora/sql/seed-corpus/* {{TARGET_PATH}}/{{EXPERIMENT}}/corpus
    cp -r {{BASE_DIR}}/fuzzing-corpora/sql/dict.txt {{TARGET_PATH}}/{{EXPERIMENT}}/dict.txt
    cp -r $PROJECT_PATH/seed-corpus/* {{TARGET_PATH}}/{{EXPERIMENT}}/corpus
    python3 $PROJECT_PATH/generate-corpus/gen_sql.py {{TARGET_PATH}}/{{EXPERIMENT}}/corpus

import '../Justfile'