
  CREATE TABLE t1(a INT);
  CREATE TABLE t2(b INT);
  INSERT INTO t2(b) VALUES(NULL);

  SELECT DISTINCT a FROM t1 FULL JOIN t2 ON true WHERE (b ISNULL);

  SELECT a FROM t1 FULL JOIN t2 ON true;

  SELECT a FROM t1 FULL JOIN t2 ON true WHERE (b ISNULL);

  SELECT DISTINCT a FROM t1 FULL JOIN t2 ON true;

  CREATE TABLE r3(x);
  CREATE TABLE r4(y INTEGER PRIMARY KEY);
  INSERT INTO r4 VALUES(55);

  SELECT 'value!' FROM r3 FULL JOIN r4 ON (y=x);

  SELECT 'value!' FROM r3 FULL JOIN r4 ON (y=x) WHERE +y=55;

  CREATE TABLE t0 (c0);
  CREATE TABLE t1 (c0);
  CREATE TABLE t2 (c0 , c1 , c2 , UNIQUE (c0), UNIQUE (c2 DESC));
  INSERT INTO t2 VALUES ('x', 'y', 'z');
  ANALYZE;
  CREATE VIEW v0(c0) AS SELECT FALSE;

  CREATE TABLE t1(a,b,c,d,e,f,g,h,PRIMARY KEY(a,b,c)) WITHOUT ROWID;
  CREATE TABLE t2(i, j);
  INSERT INTO t2 VALUES(10, 20);

  SELECT (d IS NULL) FROM t1 RIGHT JOIN t2 ON (j=33);

  CREATE INDEX i1 ON t1( (d IS NULL), d );

  SELECT (d IS NULL) FROM t1 RIGHT JOIN t2 ON (j=33);

  CREATE TABLE t0(w);
  CREATE TABLE t1(x);
  CREATE TABLE t2(y);
  CREATE TABLE t3(z);
  INSERT INTO t3 VALUES('t3val');

  SELECT * FROM t1 INNER JOIN t2 ON (0) RIGHT OUTER JOIN t3;

  SELECT * FROM t1 INNER JOIN t2 ON (0) FULL OUTER JOIN t3;

  SELECT * FROM t3 LEFT JOIN t2 ON (0);

  SELECT * FROM t0 RIGHT JOIN t1 INNER JOIN t2 ON (0) RIGHT JOIN t3

  SELECT * FROM t0 RIGHT JOIN t1 INNER JOIN t2 ON (0)

  CREATE TABLE t1(a INT);
  CREATE TABLE t2(b INT);
  INSERT INTO t1 VALUES(3);
  SELECT CASE WHEN t2.b THEN 0 ELSE 1 END FROM t1 LEFT JOIN t2 ON true;

  SELECT * FROM t1 LEFT JOIN t2 ON true WHERE CASE WHEN t2.b THEN 0 ELSE 1 END;
