SELECT 1 IN ()SELECT 1 IN (2)SELECT 1 IN (2,3,4,5,6,7,8,9)SELECT 1 NOT IN ()SELECT 1 NOT IN (2)SELECT 1 NOT IN (2,3,4,5,6,7,8,9)SELECT null IN ()SELECT null NOT IN ()
  CREATE TABLE t1(x);
  SELECT 1 IN t1;
SELECT 1 NOT IN t1SELECT null IN t1SELECT null NOT IN t1
  CREATE TABLE t2(y INTEGER PRIMARY KEY);
  SELECT 1 IN t2;
SELECT 1 NOT IN t2SELECT null IN t2SELECT null NOT IN t2
  CREATE TABLE t3(z INT UNIQUE);
  SELECT 1 IN t3;
SELECT 1 NOT IN t3SELECT null IN t3SELECT null NOT IN t3SELECT 1 IN (SELECT x+y FROM t1, t2)SELECT 1 NOT IN (SELECT x+y FROM t1,t2)SELECT null IN (SELECT x+y FROM t1,t2)SELECT null NOT IN (SELECT x+y FROM t1,t2)SELECT 1.23 IN ()SELECT 1.23 NOT IN ()SELECT 1.23 IN t1SELECT 1.23 NOT IN t1SELECT 'hello' IN ()SELECT 'hello' NOT IN ()SELECT 'hello' IN t1SELECT 'hello' NOT IN t1SELECT x'303132' IN ()SELECT x'303132' NOT IN ()SELECT x'303132' IN t1SELECT x'303132' NOT IN t1SELECT 1 IN (2,3,4)SELECT 1 NOT IN (2,3,4)SELECT 'a' IN ('b','c','d')SELECT 'a' NOT IN ('b','c','d')SELECT 1 NOT IN t4SELECT 1 IN t5SELECT 1 NOT IN t5SELECT 1 IN t6SELECT 1 NOT IN t6SELECT 'a' IN t7SELECT 'a' NOT IN t7SELECT 'a' IN t8SELECT 'a' NOT IN t8SELECT 2 IN (2,3,4,null)SELECT 3 NOT IN (2,3,4,null)SELECT 4 IN (2,3,4)SELECT 2 NOT IN (2,3,4)SELECT 'b' IN ('b','c','d')SELECT 'c' NOT IN ('b','c','d')SELECT 'd' IN ('b','c',null,'d')SELECT 'b' NOT IN (null,'b','c','d')SELECT 2 IN t4SELECT 3 NOT IN t4SELECT 4 IN t4nSELECT 2 NOT IN t4nSELECT 2 IN t5SELECT 3 NOT IN t5SELECT 2 IN t6SELECT 3 NOT IN t6SELECT 4 IN t6nSELECT 2 NOT IN t6nSELECT 'b' IN t7SELECT 'c' NOT IN t7SELECT 'c' IN t7nSELECT 'd' NOT IN t7nSELECT 'b' IN t8SELECT 'c' NOT IN t8SELECT 'c' IN t8nSELECT 'd' NOT IN t8nSELECT 'a' IN (NULL,'a'){SELECT 'a' NOT IN (NULL,'a'){{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{