release.base=1.3.9
release.number=1.3.9
release.date=16:40:02 EDT, 21 August, 2009
eclipse.ui.version=1.3.9.20090821
findbugs.website=http://findbugs.sourceforge.net
findbugs.downloads.website=http://prdownloads.sourceforge.net/findbugs
