PROJECT := 'lucene-10.4.0'
INSTRUMENT_CLASSES := 'org.apache.lucene.**'
COVERAGE_INCLUDES := 'org.apache.lucene.**'
COVERAGE_EXCLUDES := ""

build_project: build_java

prepare_corpus EXPERIMENT:
    cp -r {{BASE_DIR}}/fuzzing-corpora/text/seed-corpus/* {{TARGET_PATH}}/{{EXPERIMENT}}/corpus
    cp -r {{BASE_DIR}}/fuzzing-corpora/text/dict.txt {{TARGET_PATH}}/{{EXPERIMENT}}/dict.txt

import '../Justfile'